# Generated by Django 3.2.7 on 2021-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=150)),
                ('done', models.BooleanField()),
                ('priority', models.CharField(choices=[('LO', 'Low'), ('NO', 'Normal'), ('HI', 'High')], default='NO', max_length=2)),
                ('notification_due_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
