# Generated by Django 3.2.7 on 2021-09-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytasks',
            name='date',
            field=models.DateField(),
        ),
    ]
